FeedItem:
    type: "object"
    config:
        description: "An feed item"
        fields:
            id:
                type: "Int"
                description: "The unique ID of the item."
            isTrash:
                type: "Int"
                description: "Type of the decision: read or not read (sent to trash) the item source."
            created_at:
                type: "String"
                description: "Date and time of the item creation."
            title:
                type: "String"
                description: "Title of the item source."
            link:
                type: "String"
                description: "URI to the item source."
            dt:
                type: "String"
                description: "Date and time of item source."
